---

- name: install duckdns for dynamic dns updates and configure ssh
  hosts:
    - tag_Role_maptool
  become: yes
  handlers:
    - name: systemd daemon-reload
      systemd:
        daemon_reload: yes
  tags:
    - duckdns

  roles:
    - rofrantz.duckdns
  post_tasks:
    - name: Drop in systemd startup script for duckdns
      template:
        src: templates/duckdns_startup.service.j2
        dest: /etc/systemd/system/duckdns_startup.service
        mode: 0644
        owner: root 
      notify: systemd daemon-reload
    - name: enable duckdns startup
      systemd:
        name: duckdns_startup
        state: started
        enabled: yes

- name: install maptool
  hosts:
    - tag_Role_maptool
  become: yes
  roles:
    - maptool

